# Generated by Django 4.0 on 2023-07-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('-SELECT-', '-SELECT-'), ('chapter 1', 'chapter 1'), ('chapter 2', 'chapter 2'), ('chapter 3', 'chapter 3'), ('chapter 4', 'chapter 4')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('-SELECT-', '-SELECT-'), ('10 EM', '10 EM'), ('10 TM', '10 TM'), ('9 EM', '9 EM'), ('9 TM', '9 TM')], default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Slesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slesson', models.CharField(max_length=124)),
                ('chapter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mocktest.chapter')),
                ('sclass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mocktest.sclass')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30, null=True)),
                ('schoolname', models.CharField(max_length=30, null=True)),
                ('mandalname', models.CharField(max_length=10, null=True)),
                ('distname', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(null=True)),
                ('date1', models.DateField(auto_now_add=True)),
                ('marks', models.IntegerField(null=True)),
                ('bhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.userdetail')),
                ('slesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.slesson')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(choices=[('-SELECT-', '-SELECT-'), ('TELUGU', 'TELUGU'), ('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('MATHS', 'MATHS'), ('PHYSCI', 'PHYSCI'), ('BIOSCI', 'BIOSCI'), ('SOCIAL', 'SOCIAL')], default='TELUGU', max_length=40)),
                ('sclass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mocktest.sclass')),
            ],
        ),
        migrations.AddField(
            model_name='slesson',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mocktest.subject'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('option1', models.CharField(max_length=30, null=True)),
                ('option2', models.CharField(max_length=30, null=True)),
                ('option3', models.CharField(max_length=30, null=True)),
                ('option4', models.CharField(max_length=30, null=True)),
                ('answer', models.CharField(max_length=30, null=True)),
                ('slesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.slesson')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_ans', models.CharField(max_length=100, null=True)),
                ('que', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.question')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.testresult')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='sclass',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.sclass'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktest.subject'),
        ),
    ]
