# Generated by Django 4.0 on 2023-07-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_rename_add1_userdetail_distname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_start',
            field=models.DateTimeField(null=True),
        ),
    ]
