# Generated by Django 4.0 on 2023-07-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0003_topic_topic_end_topic_topic_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='start_time',
        ),
    ]
