# Generated by Django 4.0 on 2023-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_access_schedule_start', models.DateTimeField(blank=True, null=True)),
                ('dashboard_access_schedule_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
