# Generated by Django 4.0 on 2023-06-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_userschedule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='user',
        ),
    ]
