# Generated by Django 4.2.1 on 2023-06-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_userschedule_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
